### ISSUE TITLE
Broken on 2023 versions right now

### ISSUE THREAD

**Issue by nelsonjchen** [nelsonjchen/Colorized-Project#10]
I guess they're changing the UI underpinnings again.

**Comment by nelsonjchen** [comment]
Put out v1.0.1 with a fix for macOS at least. Not sure on later versions on other platforms. May push more bumps as needed.

**Comment by nelsonjchen** [comment]
Notes: 

Since there isn't an API, the current MO, the rough steps per update are:

1. Bump ide version in https://github.com/nelsonjchen/Colorized-Project/blob/main/gradle.properties
2. Put breakpoints on place where it hunts elements
3. Run `runPlugin` in debug mode
4. Use liberally `as Container` and `.components()` on stuff to figure out what the shape of the UI is.

Also, with the changes for v1.0.1, I've chosen to be super conservative on the UI. It will now always break until a bump is released.

**Comment by alexyalunin** [comment]
thanks, just updated from markerplace, works great!

**Comment by nelsonjchen** [comment]
Works in Windows and macOS for me.
